// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations run against the unpooled connection (Prisma 7 config no longer
  // has a separate directUrl field). The pooled DATABASE_URL is used by the
  // runtime PrismaClient, wired up in Phase 4/5.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
